### ISSUE TITLE
requirement.txt is not working

### ISSUE THREAD

**Issue by azirophale** [Anonymous-1901/TorrfLix#1]
I suggest you to create requirement.txt file using "https://pip.pypa.io/en/stable/cli/pip_freeze/ " 

and could not able to  run  torflix.py file

**Comment by Anonymous-1901** [comment]
Sure. I'll look into it and thanks!

**Comment by Anonymous-1901** [comment]
Sure I'll look into it . Also what error are you getting exactly? Excuse me I'm a newbie trying out stuff, so .

**Comment by azirophale** [comment]
I am getting below error  
Invalid requirement: '.\\requirements.txt'

**Comment by azirophale** [comment]
solved the issue with below cmd

pip install -U -r requirements.txt
